Traceback (most recent call last):
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\pm27995\AppData\Local\anaconda3\envs\qe-mini-example\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.subplot(111)                                              # location map
GSLIB.locmap_st(df,'X','Y','Porosity',xmin,xmax,ymin,ymax,pormin,pormax,
                'Porosity','X (m)','Y (m)','Porosity (fraction)',cmap)
plt.subplots_adjust(left=0.0, bottom=0.0, right=0.7, top=0.8, wspace=0.5, hspace=0.3); add_grid(); plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[9], line 2[0m
[0;32m      1[0m plt[38;5;241m.[39msubplot([38;5;241m111[39m)                                              [38;5;66;03m# location map[39;00m
[1;32m----> 2[0m GSLIB[38;5;241m.[39mlocmap_st(df,[38;5;124m'[39m[38;5;124mX[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mY[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mPorosity[39m[38;5;124m'[39m,xmin,xmax,ymin,ymax,[43mpormin[49m,pormax,
[0;32m      3[0m                 [38;5;124m'[39m[38;5;124mPorosity[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mX (m)[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mY (m)[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mPorosity (fraction)[39m[38;5;124m'[39m,cmap)
[0;32m      4[0m plt[38;5;241m.[39msubplots_adjust(left[38;5;241m=[39m[38;5;241m0.0[39m, bottom[38;5;241m=[39m[38;5;241m0.0[39m, right[38;5;241m=[39m[38;5;241m0.7[39m, top[38;5;241m=[39m[38;5;241m0.8[39m, wspace[38;5;241m=[39m[38;5;241m0.5[39m, hspace[38;5;241m=[39m[38;5;241m0.3[39m); add_grid(); plt[38;5;241m.[39mshow()

[1;31mNameError[0m: name 'pormin' is not defined

